version: '3.3'

networks:
  app-tier:
    driver: bridge

services:
  strapi:
    image: jeyluu/strapi-svc-dnt:release-1.0.7
    environment:
      - NODE_ENV=production
      - DATABASE_CLIENT=mysql
      - DATABASE_HOST=mysql-3ea9152-jeyluu-1270.g.aivencloud.com
      - DATABASE_PORT=26826
      - DATABASE_NAME=defaultdb
      - DATABASE_USERNAME=avnadmin
      - DATABASE_PASSWORD=AVNS_ilVw0peh8awyeKT1Qcf
      - JWT_SECRET=your-super-secret-key
      - ADMIN_JWT_SECRET=your-super-secret-key
      - TRANSFER_TOKEN_SALT=your-super-secret-key
      - APP_KEYS=your-super-secret-key
      - PUBLIC_URL=http://27.71.27.147:1337
      - CLOUDINARY_NAME=dnt-cloud
      - CLOUDINARY_KEY=734211622641529
      - CLOUDINARY_SECRET=wgHEUdibkkucRSG9Tc5qcvtdRvc
      - CLOUDINARY_FOLDER=strapi-uploads
      - DATABASE_SSL=true
      - DATABASE_SSL_CAPATH=/app/ca.pem
      - DATABASE_SSL_REJECT_UNAUTHORIZED=false

    ports:
      - "1337:1337"
    networks:
      - app-tier

  # mysql:
  #   image: bitnami/mysql:latest
  #   environment:
  #     - ALLOW_EMPTY_PASSWORD=yes
  #     - MYSQL_DATABASE=strapi
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - mysql_data:/bitnami/mysql/data
  #   networks:
  #     - app-tier

  # nginx:
  #   image: jeyluu/nginx:dev-0.5.4
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - strapi
  #   restart: always

volumes:
  mysql_data:
